  version: '3.8'

  services:
    postgres:
      image: postgres:15-alpine
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB} # Define o nome do banco Ãºnico
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
        - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 10s
      networks:
        - app-network

    gateway:
      image: ghcr.io/${REPO_OWNER}/gateway:${GATEWAY_IMAGE_TAG:-latest}
      ports:
        - "3000:3000"
      environment:
        - AUTH_HOST=auth-service
        - NOTIFICATION_HOST=notification-service
        - USERS_HOST=users-service
        - ROOMS_HOST=rooms-service
        - RESOURCES_HOST=resources-service
        - BOOKINGS_HOST=bookings-service
        - JWT_SECRET=${JWT_SECRET}
      depends_on:
        auth-service:
          condition: service_started
        users-service:
          condition: service_started
        rooms-service:
          condition: service_started
        resources-service:
          condition: service_started
        bookings-service:
          condition: service_started
        postgres:
          condition: service_healthy
      networks:
        - app-network

    auth-service:
      image: ghcr.io/${REPO_OWNER}/auth-service:${AUTH_IMAGE_TAG:-latest}
      ports:
        - "3001:3000"
      environment:
        - DB_HOST=${DB_HOST}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - AUTSCHEMA=${AUTSCHEMA}
        - USERS_HOST=users-service
        - JWT_SECRET=${JWT_SECRET}
      depends_on:
        postgres:
          condition: service_healthy
      networks:
        - app-network  

    users-service:
      image: ghcr.io/${REPO_OWNER}/users-service:${USER_IMAGE_TAG:-latest}
      ports:
        - "3003:3000"
      environment:
        - DB_HOST=${DB_HOST}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - USERSCHEMA=${USERSCHEMA}
        - ADMIN_NAME=${ADMIN_NAME}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      depends_on:
        postgres:
          condition: service_healthy
      networks:
        - app-network

    rooms-service:
      image: ghcr.io/${REPO_OWNER}/rooms-service:${ROOM_IMAGE_TAG:-latest}
      ports:
        - "3004:3000"
      environment:
        - DB_HOST=${DB_HOST}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - ROOMSCHEMA=${ROOMSCHEMA}
      depends_on:
        postgres:
          condition: service_healthy
      networks:
        - app-network

    resources-service:
      image: ghcr.io/${REPO_OWNER}/resources-service:${RESOURCES_IMAGE_TAG:-latest}
      ports:
        - "3005:3000"
      environment:
        - DB_HOST=${DB_HOST}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - RESOURCESSCHEMA=${RESOURCESSCHEMA}
      depends_on:
        postgres:
          condition: service_healthy
      networks:
        - app-network

    bookings-service:
      image: ghcr.io/${REPO_OWNER}/bookings-service:${BOOKING_IMAGE_TAG:-latest}
      ports:
        - "3006:3000"
      environment:
        - DB_HOST=${DB_HOST}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - BOOKINGSSCHEMA=${BOOKINGSSCHEMA}
        - ROOMS_HOST=rooms-service
      depends_on:
        postgres:
          condition: service_healthy
      networks:
        - app-network

    notification-service:
      image: ghcr.io/${REPO_OWNER}/notification-service:${NOTIFICATION_IMAGE_TAG:-latest}
      ports:
        - "3002:3000"
      environment:
        - MAIL_HOST=smtp.exemplo.com
      depends_on:
        postgres:
          condition: service_healthy
      networks:
        - app-network

  networks:
    app-network:
      driver: bridge